### ISSUE TITLE
Support of more node and npm versions

### ISSUE THREAD

**Issue by tuliren** [szanata/full_stack#1]
@szanata, thank you for creating this library. Currently it only supports Node 8.1.2. Is it possible to support some of the newer Node versions? Like Node 12?

In addition, limiting the `npm` version to `3.10.6` seems unnecessary.

**Comment by szanata** [comment]
Hey @tuliren sure, I'll test and do the necessary migrations so it can work on the latest node version. About the npm version, I agree, seems unnecessary now a days. I'll post in this thread when I create the new release.

**Comment by tuliren** [comment]
Thanks a lot!

**Comment by szanata** [comment]
@tuliren I just released the version 1.0.0, which supports node 8,10,12 and 14.
There is a small breaking change, method `.prepare` is now called `.trap`. Aside from that, all is the same.

**Comment by tuliren** [comment]
Nice, thank you!
